# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Shot by hundredrab"
subtitle: "Pictures which speak a hundred words"
author:  "Sourab Jha"
header:
 title: "Photography"
 subtitle: "by hundredrab"
footer:
 name: ""
 bio: ""
social_urls:
  twitter: "https://twitter.com/5ourab"
  instagram: "https://www.instagram.com/hundredrab/"
  linkedin: "https://www.linkedin.com/in/sourab-j/"
  github: "https://github.com/hundredrab"


theme: jekyll-theme-slate
